### ISSUE TITLE
$this->mViewFile & $this->load->view behavior?

### ISSUE THREAD

**Issue by wpraas** [waifung0207/ci_bootstrap#10]
1) $this->mViewFile = 'tests';
It will load tests.php file only

2) $this->load->view('tests',$data);
It will load tests.php file only and also pass $data array on view

I want the 2) behavior

For this, I put these lines
$this->mViewFile = 'tests';
$this->load->view('tests',$data);

This will output twice.

If I remove this line $this->mViewFile = 'tests';

I got this error:
"A PHP Error was encountered
Severity: Notice
Message: Undefined property: Tests::$mViewFile
Filename: hooks/controller.php"

Is there any way 1) will behave like 2) ?

**Comment by waifung0207** [comment]
In this project, I only use **$this->mViewFile** to define which view file to be rendered, while **$this->mViewData** are used to contain data passing to the views.

For example, you can write the code like this, then you can use the "user" array from "tests" view:

``` php
$this->mViewData['user'] = array('name' => 'wpraas');
$this->mViewFile = 'tests';
```

You may check out controllers like "backend/controllers/example.php" for a working example.

But you did raise out an issue that I felt a little bit confused for developers to work with, since I don't have much time to explain everything in details. In my next version of [CI Bootstrap 3](https://github.com/waifung0207/ci_bootstrap_3), I have changed the render method in MY_Controller's render() function and avoid using hooks instead. Hopefully it can be more easier for others to follow with.
