### ISSUE TITLE
I have a problem with the url

### ISSUE THREAD

**Issue by yampi19** [waifung0207/ci_bootstrap#12]
Not Found

The requested URL /sistema/account/signup was not found on this server.

The requested URL /sistema/example/demo/1 was not found on this server.

.

.

http://localhost:8888/sistema/backend.php/login
shows woooju, but I enter as admin screen goes blank :(

it can be happening?

**Comment by waifung0207** [comment]
Hi,

Can you please verify whether URL rewrite is enabled in your web server (e.g. Apache)?

Alternatively, you can try updating the applications/frontend/config/config.php file as follow:

``` php
$config['index_page'] = 'index.php';
```

And I would suggest you to check out my latest repository using CI3 instead of CI2:
https://github.com/waifung0207/ci_bootstrap_3/

**Comment by yampi19** [comment]
hi!!
ci_bootstrap_3 It has backend, 

as he entered the backend?

**Comment by waifung0207** [comment]
In CI Bootstrap 3, the structure is following HMVC pattern and backend system can be accessed from e.g. http://localhost/ci_bootstrap_3/admin/, where you can find the source code under folder "application/modules/admin/"
