### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by amasadi** [waifung0207/ci_bootstrap#3]
How to integrate with form validation library?

Like

$this->load->library('form_validation');
$this->form_validation->set_rules('username', 'username','required|strip_tags');

**Comment by waifung0207** [comment]
Instead of using inline rules, I made use of config file to integrate with the form validation library; please have a look on [this page](https://ellislab.com/codeigniter/user-guide/libraries/form_validation.html#savingtoconfig) (section "Saving Sets of Validation Rules to a Config File") 

From this repository, you should see a file **applications/frontend/config/form_validation.php** (also exists in backend) which stores some preset validation rules like this:

```php
$config = array(

	// Login
	'account/login' => array(
		array(
			'field'		=> 'email',
			'label'		=> 'Email',
			'rules'		=> 'required|valid_email',
		),
		array(
			'field'		=> 'password',
			'label'		=> 'Password',
			'rules'		=> 'required',
		),
	),
```

In addition, to avoid repeated code, I have built a function named **validate_form** from **helpers/MY_form_helper.php**, which helps with loading target rule set as well as setting alert message, filling in input values, redirection, etc. Otherwise you can also make use of CodeIgniter's native method to deal with form validation.
