### ISSUE TITLE
Invalid Login

### ISSUE THREAD

**Issue by easyfun89** [waifung0207/ci_bootstrap#8]
I have tried for many times to login but its always say "invalid login",,, is it true that user and password : admin and admin ?
please help me

**Comment by buoncri** [comment]
I try to help ;-)

http://localhost/ci_bootstrap_3/admin/login ... the form is precompiled with defoult value admin:admin or you can use staff:staff. For a painless setup is convenient to have php 5.5 ...

**Comment by waifung0207** [comment]
Hi,

Did you import the file "ci_bootstrap.sql" to your MySQL database? I wonder if the saved password is expired, since I made use of password_hash() and password_verify() from PHP 5.5+ directly.

Alternatively, you may override the functions hash_pw() and verify_pw() by your custom logic from this file: applications/backend/helpers/auth_helper.php

Also please feel free to check with my latest repo which make use of CI 3.0 instead: 
- https://github.com/waifung0207/ci_bootstrap_3/
